[project]
name = "agent-py"
version = "0.1.0"
description = "A simple AI assistant that helps you work with files through natural conversation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic",
    "google-generativeai",
    "python-dotenv"
]
